import { createRequire } from 'module'; import http from 'http'; import fs from 'fs'; import path from 'path';
const require = createRequire('/opt/node22/lib/node_modules/'); const { chromium } = require('playwright');
const site = process.argv[2];
const srv = http.createServer((q, r) => { const f = path.join(site, decodeURIComponent(q.url.split('?')[0]).replace(/^\//, '') || 'index.html'); if (!fs.existsSync(f) || fs.statSync(f).isDirectory()) { r.writeHead(404); r.end(); return; } r.writeHead(200, { 'content-type': f.endsWith('.json') ? 'application/json' : 'text/html; charset=utf-8' }); r.end(fs.readFileSync(f)); }).listen(0);
const base = `http://127.0.0.1:${srv.address().port}/`;
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const ctx = await b.newContext({ viewport: { width: 1300, height: 900 } });
await ctx.addInitScript(() => {
  const mem = {};
  const col = n => ({ onSnapshot(f) { setTimeout(() => f({ docs: Object.entries(mem[n] || {}).map(([id, d]) => ({ id, data: () => d })) }), 10); return () => {}; }, doc: id => ({ set: async d => { (mem[n] = mem[n] || {})[id] = d; window.__db = mem; }, delete: async () => { delete (mem[n] || {})[id]; } }) });
  const sample = async () => ({ text: 'Opening line' }); sample.json = async () => ({ score: 2, hit: ['a'], missed: ['b'], tip: 't' });
  window.claude = { use: async n => n === 'db' ? { collection: col, doc: p => col(p.split('/')[0]).doc(p.split('/')[1]) } : n === 'sample' ? sample : null };
});
const res = []; const ok = (n, c) => res.push((c ? 'PASS ' : 'FAIL ') + n);
const p = await ctx.newPage(); p.setDefaultTimeout(5000); const errs = []; p.on('pageerror', e => errs.push(e.message));
await p.goto(base + 'p8.html#s-gender--equal-in-worth-different-in-role'); await p.waitForTimeout(700);
ok('no queue/draft buttons', (await p.locator('[data-q],[data-d],[data-queue]').count()) === 0);
ok('spar link on brief', (await p.locator('article.brief >> nth=0 >> a.draft').getAttribute('href')).startsWith('spar.html#p8.'));
await p.click('[data-mode=skim]'); ok('skim hides evidence', !(await p.locator('article.brief >> nth=0 >> .r-ev').isVisible()));
await p.click('[data-mode=full]'); await p.mouse.wheel(0, 1500); await p.waitForTimeout(400);
ok('last read stored', await p.evaluate(() => !!localStorage.getItem('da2:last')));
await p.goto(base + 'index.html'); await p.waitForTimeout(900);
ok('continue strip', (await p.locator('#cont a').count()) >= 2);
await p.fill('#fq', 'hadith written'); await p.waitForTimeout(500); ok('finder results', (await p.locator('#results .res').count()) > 0);
ok('finder spar links', (await p.locator('#results a:has-text("Spar on this")').count()) > 0);
ok('no drill/queue on hub', (await p.locator('a[href="drill.html"], #open-queue').count()) === 0);
await p.goto(base + 'spar.html#p8.s-gender--equal-in-worth-different-in-role'); await p.waitForTimeout(800);
ok('spar preselects topic', (await p.locator('#s-topic').inputValue()) === 'p8#s-gender--equal-in-worth-different-in-role');
await p.goto(base + 'learn.html'); await p.waitForTimeout(800);
await p.selectOption('#f-mode', 'atk'); await p.waitForTimeout(300);
ok('attacks-only mode', (await p.locator('.where .pill').first().innerText()).toLowerCase().includes('attack'));
await p.fill('#mine', 'an answer long enough'); await p.click('#gr'); await p.waitForTimeout(400); ok('attack grading', (await p.locator('.grade').innerText()).includes('Score 2'));
console.log(res.join('\n')); console.log(errs.length ? 'PAGE ERRORS: ' + errs.join(' | ') : 'no page errors');
await b.close(); srv.close();
