import { createRequire } from 'module'; import http from 'http'; import fs from 'fs'; import path from 'path';
const require = createRequire('/opt/node22/lib/node_modules/'); const { chromium } = require('playwright');
const site = process.argv[2], out = process.argv[3];
const srv = http.createServer((q, r) => { const f = path.join(site, decodeURIComponent(q.url.split('?')[0]).replace(/^\//, '') || 'index.html'); if (!fs.existsSync(f) || fs.statSync(f).isDirectory()) { r.writeHead(404); r.end(); return; } r.writeHead(200, { 'content-type': f.endsWith('.json') ? 'application/json' : 'text/html; charset=utf-8' }); r.end(fs.readFileSync(f)); }).listen(0);
const base = `http://127.0.0.1:${srv.address().port}/`;
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const ctx = await b.newContext({ viewport: { width: 1200, height: 1000 }, colorScheme: 'light' });
await ctx.addInitScript(() => {
  const mem = {};
  const col = n => ({ onSnapshot(f) { setTimeout(() => f({ docs: Object.entries(mem[n] || {}).map(([id, d]) => ({ id, data: () => d })) }), 10); return () => {}; }, doc: id => ({ set: async d => { (mem[n] = mem[n] || {})[id] = d; window.__db = mem; }, delete: async () => { delete (mem[n] || {})[id]; } }) });
  const sample = async () => ({ text: 'x' });
  sample.json = async p => {
    if (p.includes('list the distinct claims')) return { claims: [{ claim: 'Hadith were written 200 years later', quote: 'hadith came centuries later', times: 3, tactic: 'repetition' }, { claim: 'The Quran has many versions', quote: 'there are many Qurans', times: 1, tactic: 'list' }], style: ['Fast', 'Uses lists'] };
    if (p.includes('Write a debate briefing')) return { items: [{ i: 0, da: 'Hadith were written down in the first century, not invented in the third', answer: 'Writing began in his lifetime.', followup: 'Those are hadith too', risk: 'Hammam counts unconfirmed' }, { i: 1, da: 'made up title', answer: 'Readings are not versions.', followup: '', risk: '' }], ask: ['q1', 'q2', 'q3'], avoid: ['138 hadith'], gaps: [] };
    if (p.includes('gentle, honest companion')) return { heard: 'That sounds heavy.', solid: ['Writing began early'], debated: ['How much'], open: [], next: 'Read the first argument.', read: [], crisis: p.includes('hurt myself') };
    return {};
  };
  window.claude = { use: async n => n === 'sample' ? sample : n === 'db' ? { collection: col, doc: p => col(p.split('/')[0]).doc(p.split('/')[1]) } : null };
});
const res = []; const ok = (n, c) => res.push((c ? 'PASS ' : 'FAIL ') + n);
const p = await ctx.newPage(); p.setDefaultTimeout(6000); const errs = []; p.on('pageerror', e => errs.push(e.message));
await p.goto(base + 'dossier.html'); await p.waitForTimeout(700);
await p.fill('#d-name', 'Test Debater'); await p.fill('.src textarea', 'hadith came centuries later and there are many Qurans');
await p.click('#build'); await p.waitForTimeout(800);
ok('dossier rendered', (await p.locator('.doc .item').count()) === 2);
ok('unknown title becomes gap', (await p.locator('.doc .chip.gap').count()) === 1);
ok('dossier saved to db', await p.evaluate(() => Object.keys(((window.__db || {}).dossiers) || {}).length === 1));
ok('saved list shows', (await p.locator('#saved [data-id]').count()) === 1);
await p.screenshot({ path: out + '/dossier.png', fullPage: true });
await p.goto(base + 'clinic.html'); await p.waitForTimeout(700);
await p.click('#doubts [data-i="0"]'); await p.waitForTimeout(500);
ok('clinic reply', (await p.locator('.reply').count()) === 1);
await p.fill('#q', 'sometimes I want to hurt myself'); await p.click('#ask'); await p.waitForTimeout(500);
ok('crisis box shown', (await p.locator('.crisis').count()) === 1);
await p.screenshot({ path: out + '/clinic.png', fullPage: true });
await p.goto(base + 'teen.html'); await p.waitForTimeout(700);
ok('teen cards', (await p.locator('.qc').count()) === 23);
await p.click('.qc >> nth=0 >> button'); ok('teen card opens', await p.locator('.qc >> nth=0 >> .body').isVisible());
await p.click('#chips [data-g="Hadith"]'); ok('teen filter', (await p.locator('.qc').count()) === 3);
await p.click('.qc >> nth=0 >> button'); await p.screenshot({ path: out + '/teen.png' });
console.log(res.join('\n')); console.log(errs.length ? 'PAGE ERRORS: ' + errs.join(' | ') : 'no page errors');
await b.close(); srv.close();
